// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Current.tsx": () => import("../components/mockups/Current.tsx"),
  "./components/mockups/VariantA.tsx": () => import("../components/mockups/VariantA.tsx"),
  "./components/mockups/VariantB.tsx": () => import("../components/mockups/VariantB.tsx"),
  "./components/mockups/VariantC.tsx": () => import("../components/mockups/VariantC.tsx"),
  "./components/mockups/hero-section/ConceptA.tsx": () => import("../components/mockups/hero-section/ConceptA.tsx"),
  "./components/mockups/hero-section/ConceptB.tsx": () => import("../components/mockups/hero-section/ConceptB.tsx"),
  "./components/mockups/hero-section/ConceptC.tsx": () => import("../components/mockups/hero-section/ConceptC.tsx"),
  "./components/mockups/hero-section/ConceptD.tsx": () => import("../components/mockups/hero-section/ConceptD.tsx"),
  "./components/mockups/hero-section/SurpriseA.tsx": () => import("../components/mockups/hero-section/SurpriseA.tsx"),
  "./components/mockups/hero-section/SurpriseB.tsx": () => import("../components/mockups/hero-section/SurpriseB.tsx"),
  "./components/mockups/hero-section/SurpriseC.tsx": () => import("../components/mockups/hero-section/SurpriseC.tsx"),
  "./components/mockups/hero-section/TactileA.tsx": () => import("../components/mockups/hero-section/TactileA.tsx"),
  "./components/mockups/hero-section/TactileB.tsx": () => import("../components/mockups/hero-section/TactileB.tsx"),
  "./components/mockups/hero-section/TactileC.tsx": () => import("../components/mockups/hero-section/TactileC.tsx"),
  "./components/mockups/hero-section/VibeA.tsx": () => import("../components/mockups/hero-section/VibeA.tsx"),
  "./components/mockups/hero-section/VibeB.tsx": () => import("../components/mockups/hero-section/VibeB.tsx"),
  "./components/mockups/hero-section/VibeC.tsx": () => import("../components/mockups/hero-section/VibeC.tsx")
};
