// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Current.tsx": () => import("../components/mockups/Current.tsx"),
  "./components/mockups/VariantA.tsx": () => import("../components/mockups/VariantA.tsx"),
  "./components/mockups/VariantB.tsx": () => import("../components/mockups/VariantB.tsx"),
  "./components/mockups/VariantC.tsx": () => import("../components/mockups/VariantC.tsx")
};
